[configuration]
frequency = 2                          # it means pull shards per 2 seconds, and should not be bigger than 12s.
port = 9932
rpc-method = "mantaPay_pull_ledger_diff"
db-path = ""

[server.configuration]
# all params are default values
max_request_body_size = 10 # in MB 
max_response_body_size = 10 # in MB 
max_connections = 100
max_subscriptions_per_connection = 1024
max_log_length = 4096
batch_requests_supported = true
ping_interval = 60 # in second
