[indexer.configuration]
frequency = 2 # it means pull shards per 2 seconds, and should not be bigger than 12s.
port = 7788
rpc_method = "mantaPay_pull_ledger_diff"
full_node = "ws://127.0.0.1:9800"

[server.configuration]
# all params are default values from substrate
max_request_body_size = 10485760 # 10 MB 
max_response_body_size = 10485760 # 10 MB 
max_connections = 100
max_subscriptions_per_connection = 1024
max_log_length = 4096
batch_requests_supported = true
ping_interval = 30 # in second

[db.configuration]
db_path = "indexer.db"
pool_size = 16
