[indexer.configuration]
# it means pull shards per 2 seconds, and should not be bigger than 12s.
frequency = 2
# connection backend full node
full_node = "ws://127.0.0.1:9800"
# full_node = "wss://ws.rococo.dolphin.engineering:443"
# indexer service port
port = 7788
# indexer monitoring port
prometheus_port = 7789

[server.configuration]
# all params are default values from substrate
max_request_body_size = 10 # 10 MB 
max_response_body_size = 10 # 10 MB 
max_connections = 1000
max_subscriptions_per_connection = 1024
max_log_length = 4096
batch_requests_supported = true
ping_interval = 30 # in second

[db.configuration]
# sqlite db file path
# db_path = "latest-dolphin-shards.db"
db_path = "local_sync.db"
# connection pool size.
pool_size = 16
