name: Check Build

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1
    - name: Build && Test
      run: cargo build
    - name: Lints check
      run: cargo clippy -- -D warnings
    - name: Fmt check
      run: cargo fmt --all -- --check
