name: Integration Test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [16.x, 17.x]

    steps:
      - uses: actions/checkout@v2
      - name: Indexer Build
        run: cargo build --release
      - uses: borales/actions-yarn@v3.0.0
      - uses: actions/checkout@v2
        with:
          repository: paritytech/polkadot-launch
          path: polkadot-launch
      - name: fetch and chmod polkadot
        run: |
          mkdir $HOME/.local/bin/
          curl -L -o $HOME/.local/bin/polkadot https://github.com/paritytech/polkadot/releases/download/v0.9.26/polkadot
          chmod +x $HOME/.local/bin/polkadot
      - name: fetch and chmod manta
        run: |
          curl -L -o $HOME/.local/bin/manta https://github.com/Manta-Network/Manta/releases/download/v3.4.3/manta
          chmod +x $HOME/.local/bin/manta
      - name: Start Relaychain Network with Calamari
        run: |
          cd ./polkadot-launch
          yarn build
          yarn start ./github/resources/dolphin.json &>/dev/null &
      - name: Start Indexer
        run: |
          cd ${{ github.workspace }}
          ./target/release/manta-indexer &>/dev/null &
      - name: Check Block Production
        run: |
          cd ./tests/integration-tests
          yarn
          yarn block-production
      - name: Run Integration Test
        run: |
          cd tests/integration-tests
          yarn
          yarn test-relayer
